// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA5UaFExBgyfpiIytxJPV0WF8pCN9gh6aw',
    appId: '1:510666942509:web:5b793092ba15e2b34df0a4',
    messagingSenderId: '510666942509',
    projectId: 'todo-app-6587f',
    authDomain: 'todo-app-6587f.firebaseapp.com',
    storageBucket: 'todo-app-6587f.appspot.com',
    measurementId: 'G-LLSWWL7ZLJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBHMdkdff3v_qOTmGoP2T0yJ0N6NjmHi2I',
    appId: '1:510666942509:android:39ae6f996d39bf634df0a4',
    messagingSenderId: '510666942509',
    projectId: 'todo-app-6587f',
    storageBucket: 'todo-app-6587f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD0opoN72Ss4l1Y_LBDUowtnlySLvXtZTQ',
    appId: '1:510666942509:ios:b72f436df7d478cc4df0a4',
    messagingSenderId: '510666942509',
    projectId: 'todo-app-6587f',
    storageBucket: 'todo-app-6587f.appspot.com',
    iosBundleId: 'com.example.todoAppApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD0opoN72Ss4l1Y_LBDUowtnlySLvXtZTQ',
    appId: '1:510666942509:ios:06673a2ef8a9d3064df0a4',
    messagingSenderId: '510666942509',
    projectId: 'todo-app-6587f',
    storageBucket: 'todo-app-6587f.appspot.com',
    iosBundleId: 'com.example.todoAppApp.RunnerTests',
  );
}
